#!/bin/bash

DEFAULT_PATH="$HOME/Downloads/Git/letup/pcma-lists"
CURRENT_DIR="$(realpath .)"

LIST_DIR="$(realpath .)/pcma-lists"
if [ "$CURRENT_DIR" == "$HOME/.local/bin" ]; then
    read -p "Do you want to install in default path ($DEFAULT_PATH)? [y/n] " -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        read -p "Enter custom path: " -r LIST_DIR
    fi
fi

PACMAN_LIST="$LIST_DIR/pacman-packages"
AUR_LIST="$LIST_DIR/aur-packages"

mkdir -p "$LIST_DIR"
touch "$PACMAN_LIST" "$AUR_LIST"

if command -v paru &> /dev/null; then
    AUR_HELPER="paru"
elif command -v yay &> /dev/null; then
    AUR_HELPER="yay"
else
    echo "No aur helper is installed"
    echo "Cannot use -A flag and aur installation"
fi

add_to_list() {
    local file="$1"
    shift
    local pkgs=("$@")

    for pkg in "${pkgs[@]}"; do
        if ! grep -Fxq "$pkg" "$file"; then
            echo "$pkg" >> "$file"
            echo " -> $pkg added"
        else
            echo " !> $pkg already in"
        fi
    done
}

MODE="$1"

case "$MODE" in
    -P)
        shift
        if [ $# -eq 0 ]; then
            echo "No packages"
            exit 1
        fi

        echo " :%: installing with PACMAN"

        if sudo pacman -S "$@"; then
            add_to_list "$PACMAN_LIST" "$@"
        else
            echo "Installation failed"
            exit 1
        fi
        ;;
    -A)
        shift
        if [ $# -eq 0 ]; then
            echo "No packages"
            exit 1
        fi

        echo " :%: installing with AUR HELPER"
        if "$AUR_HELPER" -S "$@"; then
            add_to_list "$AUR_LIST" "$@"
        else
            echo "Installation failed"
            exit 1
        fi
        ;;
    -I)
        shift
        case "$1" in
            pacman)
                if ! sudo pacman -S - < "$PACMAN_LIST"; then
                    pacman -S - < "$PACMAN_LIST"
                fi
                ;;
            aur)
                "$AUR_HELPER" -S - < "$AUR_LIST"
                ;;
            *)
                echo "Custom lists not supported yet"
                exit 0
                ;;
        esac
        ;;
    -l)
        if command -v bat &> /dev/null; then
            bat "$PACMAN_LIST"
            bat "$AUR_LIST"
        else
            cat "$PACMAN_LIST"
            cat "$AUR_LIST"
        fi
        ;;
    *)
        sudo pacman "$@"
        ;;
esac
