#!/usr/bin/env python

import json
import os
import sys
from argparse import ArgumentParser
from pathlib import Path

DEFAULT_PACKAGES_PATH = Path(__file__).parent / "packages"


def is_available_command(command: str) -> bool:
    return os.system(f"command -v {command}") == 0


def parse_packages_path(packages_path: Path) -> tuple[list[str], list[str]]:
    if not packages_path.exists():
        print("Packages path not found")
        sys.exit(1)

    with open(packages_path, "r") as f:
        packages = json.load(f)

    return (packages["pacman"], packages["aur"])


def get_aur_helper() -> str:
    if is_available_command("paru"):
        return "paru"
    elif is_available_command("yay"):
        return "yay"
    else:
        print("Please install paru or yay")
        sys.exit(1)


def intall_packages(packages_path: Path) -> None:
    aur_helper = get_aur_helper()
    pacman_packages, aur_packages = parse_packages_path(packages_path)

    if pacman_packages:
        os.system(f"sudo pacman -S --needed {' '.join(pacman_packages)}")

    if aur_packages:
        os.system(f"{aur_helper} -S --needed {' '.join(aur_packages)}")


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument(
        "--packages-path",
        type=Path,
        default=DEFAULT_PACKAGES_PATH,
        help="Path to packages json file",
    )
    parser.add_argument("command", type=str, help="Command to execute")
    parser.add_argument(
        "packages", nargs="+", help="Packages to install", required=False
    )

    args = parser.parse_args()

    print(args)
    # if args.command == "install" or args.command == "i":
    #     intall_packages(args.packages_path)
    # elif args.command == "add" or args.command == "a":
    #     pass


if __name__ == "__main__":
    main()
